export const productos = [
  // =========================================
  // ACCESORIOS
  // =========================================

  {
    id: 1,
    nombre: "Aros acero Las Oreiro 30667",
    categoria: "Accesorios",
    precio: 21000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 2,
    nombre: "Aros acero Las Oreiro 30664",
    categoria: "Accesorios",
    precio: 20000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 3,
    nombre: "Aros acero Las Oreiro 30685",
    categoria: "Accesorios",
    precio: 14500,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 4,
    nombre: "Aros acero Las Oreiro 30691",
    categoria: "Accesorios",
    precio: 16000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 5,
    nombre: "Aros acero Las Oreiro 30680",
    categoria: "Accesorios",
    precio: 18500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 6,
    nombre: "Aros acero Las Oreiro corazón con Strass",
    categoria: "Accesorios",
    precio: 20000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 7,
    nombre: "Aros acero Las Oreiro 30690",
    categoria: "Accesorios",
    precio: 20000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 8,
    nombre: "Pulsera acero Las Oreiro 30730",
    categoria: "Accesorios",
    precio: 16000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 9,
    nombre: "Pulsera acero Las Oreiro 30709",
    categoria: "Accesorios",
    precio: 23000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 10,
    nombre: "Pulsera acero Las Oreiro 30722",
    categoria: "Accesorios",
    precio: 16000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 11,
    nombre: "Pulsera acero Las Oreiro 30720",
    categoria: "Accesorios",
    precio: 16800,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 12,
    nombre: "Pulsera acero Las Oreiro 30715",
    categoria: "Accesorios",
    precio: 20000,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // PESTAÑAS
  // =========================================

  {
    id: 13,
    nombre: "Pestañas 30D-40D Naez Mix",
    categoria: "Pestañas",
    precio: 13500,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 14,
    nombre: "Kit de pestañas 20D-30D-40D-50D Naez",
    categoria: "Pestañas",
    precio: 16000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 15,
    nombre: "Kit de pestañas 10D-20D-30D-40D Naez",
    categoria: "Pestañas",
    precio: 14000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 16,
    nombre: "Pestañas autoadhesivas Naez BC2803",
    categoria: "Pestañas",
    precio: 11000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 17,
    nombre: "Pestañas autoadhesivas Naez",
    categoria: "Pestañas",
    precio: 7500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 18,
    nombre: "Pegamento para pestañas postizas",
    categoria: "Pestañas",
    precio: 3000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 19,
    nombre: "Pegamento para pestañas",
    categoria: "Pestañas",
    precio: 2500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 20,
    nombre: "Bigudíes rosa Cherimoya x6",
    categoria: "Pestañas",
    precio: 2700,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 21,
    nombre: "Bigudíes Miss Kiss Queen",
    categoria: "Pestañas",
    precio: 2500,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // PERFUMERÍA
  // =========================================

  {
    id: 22,
    nombre: "Perfume tubito árabe Mandarín Sky",
    categoria: "Perfumes",
    precio: 5000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 23,
    nombre: "Perfume tubito árabe Gold Edition",
    categoria: "Perfumes",
    precio: 5000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 24,
    nombre: "Aromas Alma Botánica Biogreen 330ml",
    categoria: "Perfumes",
    precio: 16500,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // CUIDADO PERSONAL
  // =========================================

  {
    id: 25,
    nombre: "Parche para nariz puntos negros Sandía",
    categoria: "Cuidado personal",
    precio: 2500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 26,
    nombre: "Parche para nariz puntos negros Palta",
    categoria: "Cuidado personal",
    precio: 2500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 27,
    nombre: "Parche para acné corazones TYL",
    categoria: "Cuidado personal",
    precio: 5000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 28,
    nombre: "Manteca de cacao Nivea sin color",
    categoria: "Cuidado personal",
    precio: 3000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 29,
    nombre: "Gel post solar refrescante Aloe Vera",
    categoria: "Cuidado personal",
    precio: 7500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 30,
    nombre: "Peine",
    categoria: "Cuidado personal",
    precio: 3500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 31,
    nombre: "Cepillo de pelo Pratys",
    categoria: "Cuidado personal",
    precio: 9500,
    imagen: "",
    destacado: true,
    stock: true,
  },

  // =========================================
  // UÑAS
  // =========================================

  {
    id: 32,
    nombre: "Base Coat Meliné 15ml",
    categoria: "Insumos uñas",
    precio: 11000,
    imagen: "",
    destacado: true,
    stock: true,
  },

  // =========================================
  // ELECTRÓNICA
  // =========================================

  {
    id: 33,
    nombre: "Linterna UV LED Charm Limit",
    categoria: "Electrónica",
    precio: 6500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 34,
    nombre: "Tira luz neón 5mts con control y enchufe",
    categoria: "Electrónica",
    precio: 35000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 35,
    nombre: "Pila AAA",
    categoria: "Electrónica",
    precio: 1000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 36,
    nombre: "Secador de pelo",
    categoria: "Electrónica",
    precio: 35000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 37,
    nombre: "Set de buclera y cepillo secador",
    categoria: "Electrónica",
    precio: 60000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 38,
    nombre: "Auriculares inalámbricos",
    categoria: "Electrónica",
    precio: 35000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 39,
    nombre: "Auriculares inalámbricos",
    categoria: "Electrónica",
    precio: 20000,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // LIBRERÍA
  // =========================================

  {
    id: 40,
    nombre: "Fibras marcadores tubo x12",
    categoria: "Librería",
    precio: 5000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 41,
    nombre: "Lapicera gel negra",
    categoria: "Librería",
    precio: 1000,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // BAZAR / REGALERÍA
  // =========================================

  {
    id: 42,
    nombre: "Kit termo + mate + bombilla Stanley",
    categoria: "Bazar",
    precio: 65000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 43,
    nombre: "Velas para hornillo x10",
    categoria: "Regalería",
    precio: 4000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 44,
    nombre: "Scrunchie terciopelo",
    categoria: "Accesorios",
    precio: 3000,
    imagen: "",
    destacado: false,
    stock: true,
  },

  // =========================================
  // PRODUCTOS EXTRA PARA LA DEMO
  // =========================================
  // Estos completan los 60 para poder probar
  // filtros, ordenar y "Mostrar más".

  {
    id: 45,
    nombre: "Mini lámpara LED a pila",
    categoria: "Electrónica",
    precio: 8500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 46,
    nombre: "Depiladora recargable rosa",
    categoria: "Electrónica",
    precio: 25000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 47,
    nombre: "Lámpara USB luz flexible",
    categoria: "Electrónica",
    precio: 7000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 48,
    nombre: "Planchita de pelo Nano Titanium",
    categoria: "Electrónica",
    precio: 45000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 49,
    nombre: "Buclera",
    categoria: "Electrónica",
    precio: 30000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 50,
    nombre: "Set cuidado facial",
    categoria: "Cuidado personal",
    precio: 12500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 51,
    nombre: "Mascarilla facial hidratante",
    categoria: "Cuidado personal",
    precio: 3500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 52,
    nombre: "Gloss labial",
    categoria: "Maquillaje",
    precio: 5500,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 53,
    nombre: "Delineador negro",
    categoria: "Maquillaje",
    precio: 4500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 54,
    nombre: "Máscara de pestañas",
    categoria: "Maquillaje",
    precio: 6500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 55,
    nombre: "Set de brochas",
    categoria: "Maquillaje",
    precio: 12000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 56,
    nombre: "Esmalte semipermanente",
    categoria: "Insumos uñas",
    precio: 6500,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 57,
    nombre: "Top Coat",
    categoria: "Insumos uñas",
    precio: 9000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 58,
    nombre: "Kit manicura",
    categoria: "Insumos uñas",
    precio: 15000,
    imagen: "",
    destacado: true,
    stock: true,
  },
  {
    id: 59,
    nombre: "Neceser",
    categoria: "Marroquinería",
    precio: 18000,
    imagen: "",
    destacado: false,
    stock: true,
  },
  {
    id: 60,
    nombre: "Cartera pequeña",
    categoria: "Marroquinería",
    precio: 28000,
    imagen: "",
    destacado: true,
    stock: true,
  },
];